# Generated by Django 3.1.7 on 2021-08-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stegnograph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manupulation',
            name='encrypted_image',
        ),
        migrations.RemoveField(
            model_name='manupulation',
            name='hide_image',
        ),
        migrations.RemoveField(
            model_name='manupulation',
            name='hide_inside',
        ),
        migrations.AddField(
            model_name='manupulation',
            name='box_image_path',
            field=models.ImageField(blank=True, upload_to="'media"),
        ),
        migrations.AddField(
            model_name='manupulation',
            name='container_image_path',
            field=models.ImageField(blank=True, upload_to="'media"),
        ),
        migrations.AddField(
            model_name='manupulation',
            name='encrypted_image_path',
            field=models.ImageField(blank=True, upload_to="'media"),
        ),
    ]
