# Generated by Django 3.1.7 on 2021-08-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stegnograph', '0006_auto_20210821_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manupulation',
            name='box_image_path',
            field=models.ImageField(blank=True, upload_to='2182021 221253'),
        ),
        migrations.AlterField(
            model_name='manupulation',
            name='container_image_path',
            field=models.ImageField(blank=True, upload_to='2182021 221253'),
        ),
        migrations.AlterField(
            model_name='manupulation',
            name='encrypted_image_path',
            field=models.ImageField(blank=True, upload_to='2182021 221253'),
        ),
    ]
