# Generated by Django 3.1.7 on 2021-08-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stegnograph', '0007_auto_20210821_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manupulation',
            name='box_image_path',
            field=models.ImageField(blank=True, upload_to='2382021 212413'),
        ),
        migrations.AlterField(
            model_name='manupulation',
            name='container_image_path',
            field=models.ImageField(blank=True, upload_to='2382021 212413'),
        ),
        migrations.AlterField(
            model_name='manupulation',
            name='encrypted_image_path',
            field=models.ImageField(blank=True, upload_to='2382021 212413'),
        ),
    ]
