# Generated by Django 3.1.7 on 2021-08-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stegnograph', '0008_auto_20210823_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manupulation',
            name='box_image_path',
            field=models.ImageField(blank=True, upload_to='2382021:22857'),
        ),
        migrations.AlterField(
            model_name='manupulation',
            name='container_image_path',
            field=models.ImageField(blank=True, upload_to='2382021:22857'),
        ),
        migrations.AlterField(
            model_name='manupulation',
            name='encrypted_image_path',
            field=models.ImageField(blank=True, upload_to='2382021:22857'),
        ),
    ]
