# Generated by Django 3.1.7 on 2021-11-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stegnograph', '0013_auto_20210828_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manupulation',
            name='box_image_path',
            field=models.ImageField(blank=True, upload_to='8112021_22427'),
        ),
        migrations.AlterField(
            model_name='manupulation',
            name='container_image_path',
            field=models.ImageField(blank=True, upload_to='8112021_22427'),
        ),
        migrations.AlterField(
            model_name='manupulation',
            name='encrypted_image_path',
            field=models.ImageField(blank=True, upload_to='8112021_22427'),
        ),
    ]
